import logging
from typing import Dict, Any
from services.ollama_client import OllamaClient

logger = logging.getLogger(__name__)

RESUME_PARSER_SYSTEM_PROMPT = """
You are an expert ATS (Applicant Tracking System) parser and HR analyst.
Your task is to extract structured information from the provided resume text.
You MUST output ONLY valid JSON matching the exact schema below. Do not include markdown formatting or extra text.

{
  "candidate_name": "Full name",
  "email": "Email address",
  "phone": "Phone number",
  "location": "City, Country or Region",
  "total_experience": "Total years of experience as a number or string",
  "roles": ["List of job titles held"],
  "skills": ["Combined list of all skills"],
  "technical_skills": ["Programming languages, frameworks, etc."],
  "soft_skills": ["Leadership, communication, etc."],
  "projects": ["Brief description of key projects"],
  "certifications": ["List of certifications"],
  "education": ["Degrees and institutions"],
  "tools": ["Software, IDEs, platforms"],
  "industries": ["e.g. Finance, Healthcare, Tech"],
  "ats_keywords": ["Crucial buzzwords for ATS matching"],
  "summary": "1-2 sentence professional summary generated by you based on the resume",
  "confidence_score": "0-100 score of how well the resume was parsed"
}
"""

class ResumeParserService:
    @staticmethod
    def parse_resume(text: str) -> Dict[str, Any]:
        """
        Parse raw resume text into structured JSON using Ollama (Llama 3)
        """
        prompt = f"Parse the following resume text:\n\n{text}"
        
        try:
            parsed_data = OllamaClient.generate_json(
                prompt=prompt,
                system=RESUME_PARSER_SYSTEM_PROMPT
            )
            return parsed_data
        except Exception as e:
            logger.error(f"Failed to parse resume: {e}")
            return {}
